version: '3'

services:

    nginx:
        container_name: nginx
        image: nginx:latest
        restart: always
        ports:
            - 80:80
        command: ["nginx", "-g", "daemon off;"]

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        command: redis-server --appendonly yes
        ports:
            - 6379:6379

    consul-server:
        container_name: consul_server
        image: consul:latest
        ports:
            - 8500:8500
            - 8600:8600
        command: consul agent -server -ui -node=server -bootstrap-expect=1 -enable-script-checks -client=0.0.0.0 -data-dir /tmp/consul

    consul-client:
        container_name: consul_client
        image: consul:latest
        command: consul agent -node=client -join=consul-server -enable-script-checks -data-dir /tmp/consul
        volumes:
            - ./redis.json:/consul/config/redis.json
            - ./web.json:/consul/config/web.json
        depends_on:
            - consul-server
